"""add SDE industry tables

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-14 14:35:15.306463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sde_imports',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('build_number', sa.BigInteger(), nullable=False),
    sa.Column('release_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_checksum', sa.String(length=64), nullable=False),
    sa.Column('row_counts', sa.JSON(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('build_number > 0', name=op.f('ck_sde_imports_build_number_positive')),
    sa.CheckConstraint('char_length(source_checksum) = 64', name=op.f('ck_sde_imports_source_checksum_sha256_length')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sde_imports')),
    sa.UniqueConstraint('build_number', name=op.f('uq_sde_imports_build_number'))
    )
    op.create_table('eve_categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('last_seen_import_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['last_seen_import_id'], ['sde_imports.id'], name=op.f('fk_eve_categories_last_seen_import_id_sde_imports'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('category_id', name=op.f('pk_eve_categories'))
    )
    op.create_table('industry_activity_types',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('last_seen_import_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['last_seen_import_id'], ['sde_imports.id'], name=op.f('fk_industry_activity_types_last_seen_import_id_sde_imports'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('activity_id', name=op.f('pk_industry_activity_types')),
    sa.UniqueConstraint('code', name=op.f('uq_industry_activity_types_code'))
    )
    op.create_table('eve_groups',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('last_seen_import_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['eve_categories.category_id'], name=op.f('fk_eve_groups_category_id_eve_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['last_seen_import_id'], ['sde_imports.id'], name=op.f('fk_eve_groups_last_seen_import_id_sde_imports'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('group_id', name=op.f('pk_eve_groups'))
    )
    op.create_index(op.f('ix_eve_groups_category_id'), 'eve_groups', ['category_id'], unique=False)
    op.create_table('eve_types',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('last_seen_import_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['eve_groups.group_id'], name=op.f('fk_eve_types_group_id_eve_groups'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['last_seen_import_id'], ['sde_imports.id'], name=op.f('fk_eve_types_last_seen_import_id_sde_imports'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('type_id', name=op.f('pk_eve_types'))
    )
    op.create_index(op.f('ix_eve_types_group_id'), 'eve_types', ['group_id'], unique=False)
    op.create_index(op.f('ix_eve_types_name'), 'eve_types', ['name'], unique=False)
    op.create_table('blueprints',
    sa.Column('blueprint_type_id', sa.Integer(), nullable=False),
    sa.Column('max_production_limit', sa.Integer(), nullable=True),
    sa.Column('last_seen_import_id', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('max_production_limit IS NULL OR max_production_limit > 0', name=op.f('ck_blueprints_max_production_limit_positive')),
    sa.ForeignKeyConstraint(['blueprint_type_id'], ['eve_types.type_id'], name=op.f('fk_blueprints_blueprint_type_id_eve_types'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['last_seen_import_id'], ['sde_imports.id'], name=op.f('fk_blueprints_last_seen_import_id_sde_imports'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('blueprint_type_id', name=op.f('pk_blueprints'))
    )
    op.create_table('industry_activities',
    sa.Column('blueprint_type_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('time_seconds', sa.Integer(), nullable=False),
    sa.Column('last_seen_import_id', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('time_seconds > 0', name=op.f('ck_industry_activities_time_seconds_positive')),
    sa.ForeignKeyConstraint(['activity_id'], ['industry_activity_types.activity_id'], name=op.f('fk_industry_activities_activity_id_industry_activity_types'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['blueprint_type_id'], ['blueprints.blueprint_type_id'], name=op.f('fk_industry_activities_blueprint_type_id_blueprints'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_seen_import_id'], ['sde_imports.id'], name=op.f('fk_industry_activities_last_seen_import_id_sde_imports'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('blueprint_type_id', 'activity_id', name=op.f('pk_industry_activities'))
    )
    op.create_table('industry_activity_materials',
    sa.Column('blueprint_type_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('material_type_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('last_seen_import_id', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_industry_activity_materials_quantity_positive')),
    sa.ForeignKeyConstraint(['blueprint_type_id', 'activity_id'], ['industry_activities.blueprint_type_id', 'industry_activities.activity_id'], name=op.f('fk_industry_activity_materials_blueprint_type_id_industry_activities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_seen_import_id'], ['sde_imports.id'], name=op.f('fk_industry_activity_materials_last_seen_import_id_sde_imports'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['material_type_id'], ['eve_types.type_id'], name=op.f('fk_industry_activity_materials_material_type_id_eve_types'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('blueprint_type_id', 'activity_id', 'material_type_id', name=op.f('pk_industry_activity_materials'))
    )
    op.create_index('ix_industry_activity_materials_material_type_id', 'industry_activity_materials', ['material_type_id'], unique=False)
    op.create_table('industry_activity_products',
    sa.Column('blueprint_type_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('product_type_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('last_seen_import_id', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_industry_activity_products_quantity_positive')),
    sa.ForeignKeyConstraint(['blueprint_type_id', 'activity_id'], ['industry_activities.blueprint_type_id', 'industry_activities.activity_id'], name=op.f('fk_industry_activity_products_blueprint_type_id_industry_activities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_seen_import_id'], ['sde_imports.id'], name=op.f('fk_industry_activity_products_last_seen_import_id_sde_imports'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_type_id'], ['eve_types.type_id'], name=op.f('fk_industry_activity_products_product_type_id_eve_types'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('blueprint_type_id', 'activity_id', 'product_type_id', name=op.f('pk_industry_activity_products'))
    )
    op.create_index('ix_industry_activity_products_product_type_id', 'industry_activity_products', ['product_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_industry_activity_products_product_type_id', table_name='industry_activity_products')
    op.drop_table('industry_activity_products')
    op.drop_index('ix_industry_activity_materials_material_type_id', table_name='industry_activity_materials')
    op.drop_table('industry_activity_materials')
    op.drop_table('industry_activities')
    op.drop_table('blueprints')
    op.drop_index(op.f('ix_eve_types_name'), table_name='eve_types')
    op.drop_index(op.f('ix_eve_types_group_id'), table_name='eve_types')
    op.drop_table('eve_types')
    op.drop_index(op.f('ix_eve_groups_category_id'), table_name='eve_groups')
    op.drop_table('eve_groups')
    op.drop_table('industry_activity_types')
    op.drop_table('eve_categories')
    op.drop_table('sde_imports')
    # ### end Alembic commands ###
